workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  DEPLOY_SERVER_HOST: "35.180.61.79"
  APP_ENDPOINT: http://ec2-35-180-61-79.eu-west-3.compute.amazonaws.com

stages:
  - build
  - deploy

.build:
  stage: build
  tags:
    - ec2
    - shell
    - remote
  variables:
    MS_NAME: ""
    MS_VERSION: ""
  before_script:
    - cd $MS_NAME
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/microservice/$MS_NAME
    - export IMAGE_TAG=$MS_VERSION
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

build_frontend:
  extends: .build
  variables:
    MS_NAME: frontend
    MS_VERSION: "1.3"
  only:
    changes:
      - "frontend/**/*"   

build_products:
  extends: .build
  variables:
    MS_NAME: products
    MS_VERSION: "1.8"
  only:
    changes:
      - "products/**/*"      

build_shopping_cart:
  extends: .build
  variables:
    MS_NAME: shopping-cart
    MS_VERSION: "1.1"
  only:
    changes:
      - "shopping-cart/**/*"

.deploy:
  stage: deploy
  tags:
    - ec2
    - shell
    - remote
  variables:
    MS_NAME: ""
    MS_VERSION: ""
    APP_PORT: ""
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
    - export IMAGE_NAME=$CI_REGISTRY_IMAGE/microservice/$MS_NAME
    - export IMAGE_TAG=$MS_VERSION
  script:
    - scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ./docker-compose.yaml ubuntu@$DEPLOY_SERVER_HOST:/home/ubuntu
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$DEPLOY_SERVER_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&

      export COMPOSE_PROJECT_NAME=$MS_NAME &&
      export DC_IMAGE_NAME=$IMAGE_NAME &&
      export DC_IMAGE_TAG=$IMAGE_TAG &&
      export DC_APP_PORT=$APP_PORT &&
      
      docker network create micro_service || true &&
      docker-compose down &&
      docker-compose up -d"
  environment:
    name: development
    url: $APP_ENDPOINT     

deploy_frontend:
  extends: .deploy
  variables:
    MS_NAME: frontend
    MS_VERSION: "1.3"
    APP_PORT: 3000
  only:
    changes:
      - "frontend/**/*"

deploy_products:
  extends: .deploy
  variables:
    MS_NAME: products
    MS_VERSION: "1.8"
    APP_PORT: 3001
  only:
    changes:
      - "products/**/*"

deploy_shopping_cart:
  extends: .deploy
  variables:
    MS_NAME: shopping-cart
    MS_VERSION: "1.1"
    APP_PORT: 3002
  only:
    changes:
      - "shopping-cart/**/*"          
